apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: queue-server
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/DubaiCookie/queue-server.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true       # 삭제된 리소스 자동 제거
      selfHeal: true    # 수동 변경이 생겨도 Git 상태로 자동 복구
    syncOptions:
      - CreateNamespace=true
