apiVersion: v1
kind: ConfigMap
metadata:
  name: queue-server-config
  namespace: default
data:
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  QUEUE_MOCK_ENABLED: "true"
