apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-server
  template:
    metadata:
      labels:
        app: queue-server
    spec:
      containers:
        - name: queue-server
          image: amdp-registry.skala-ai.com/skala26a-cloud/team3-queue-server:latest
          ports:
            - containerPort: 8079
          envFrom:
            - configMapRef:
                name: queue-server-config
